# Project: Projeto1
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainTarExtra6.o
LINKOBJ  = mainTarExtra6.o
LIBS     = -L"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/lib" -L"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/include" -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/include" -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/Eullen/Downloads/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = tarExtra6.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainTarExtra6.o: mainTarExtra6.c
	$(CPP) -c mainTarExtra6.c -o mainTarExtra6.o $(CXXFLAGS)
